ALTER TABLE invocation ADD COLUMN type TEXT DEFAULT 'REAL_TIME';
ALTER TABLE invocation ALTER COLUMN created TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE invocation ALTER COLUMN deadline TYPE TIMESTAMP WITH TIME ZONE;
