/*
 * Copyright (c) 2019. SailPoint Technologies, Inc. All rights reserved.
 */
package com.sailpoint.notification.context.common.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import org.joda.time.DateTime;

import java.util.Map;

/**
 * GlobalContext DynamoDB entity.
 */
@DynamoDBTable(tableName = "notification_global_context")
public class GlobalContextEntity {

	private String _tenant;

	private String _id;

	private DateTime _created;

	private DateTime modified;

	private Map<String, Object> _attributes;

	private Long version;

	@DynamoDBHashKey(attributeName = "tenant")
	public String getTenant() {
		return _tenant;
	}

	public void setTenant(String tenant) {
		_tenant = tenant;
	}

	@DynamoDBRangeKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return _id;
	}

	public void setId(String id) {
		_id = id;
	}

	@DynamoDBTypeConvertedTimestamp
	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	public DateTime getCreated() {
		return _created;
	}

	public void setCreated(DateTime created) {
		_created = created;
	}

	@DynamoDBTypeConvertedTimestamp
	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	public DateTime getModified() {
		return modified;
	}

	public void setModified(DateTime modified) {
		this.modified = modified;
	}

	@DynamoDBTypeConvertedJson
	public Map<String, Object> getAttributes() {
		return _attributes;
	}

	public void setAttributes(Map<String, Object> attributes) {
		_attributes = attributes;
	}

	@DynamoDBVersionAttribute
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
}