/*
 * Copyright (C) 2018-2019 SailPoint Technologies, Inc.  All rights reserved.
 */
package com.sailpoint.audit.service;

public enum FeatureFlags {
	CLEANUP_BULKUPLOAD_CONFIG,
	BULK_UPLOAD_AUDIT_EVENTS,
	BULK_UPLOAD_AUDIT_EVENTS_COUNT,
	BULK_UPLOAD_AUDIT_EVENTS_RESET,
	BULK_UPLOAD_AUDIT_EVENTS_CREATE_INDEX,
	BULK_SYNC_S3_AUDIT_EVENTS,
	BULK_SYNC_S3_AUDIT_EVENTS_COUNT,
	BULK_SYNC_S3_AUDIT_EVENTS_RESET,
	BULK_SYNC_AUDIT_EVENTS,
	BULK_SYNC_AUDIT_EVENTS_COUNT,
	BULK_SYNC_AUDIT_EVENTS_RESET,
	PROVISION_ATHENA_TABLE,
	PUBLISH_ALL_AUDIT_EVENTS,
	SP_AUDIT_PROVISION_ATHENA_TABLE,
	WRITE_AUDIT_DATA_IN_PARQUET,
	PLTDP_AUDIT_ONETIME_BULKSYNC,
	PLTDP_ONETIME_BULKSYNC_CUSTOM,
	PLTDP_CRUD_DOMAIN_BULKSYNC,
	PLTDP_PERSIST_TO_CIS_MYSQL,
	PLTDP_PERSIST_TO_S3_BY_TIME,
	PLTDP_ADD_ATHENA_PARTIONS_CUSTOM
}
