version: '3'

networks:
  sp-scheduler-integration-test:
    driver: bridge

services:
  tests:
    image: scheduler
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    environment:
      ATLAS_DB_HOST: postgres:5432
      ATLAS_DB_NAME: postgres
      ATLAS_DB_USER: postgres
      ATLAS_DB_PASSWORD: postgres
      MAX_DB_CONNECTIONS: 8
    depends_on:
      - postgres
    networks:
      - sp-scheduler-integration-test
  postgres:
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    restart: on-failure
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    networks:
      - sp-scheduler-integration-test
