/*
 * Copyright (c) 2019. SailPoint Technologies, Inc. All rights reserved.
 */
package com.sailpoint.notification.orgpreferences.repository.impl.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;

import java.util.Date;
import java.util.List;

/**
 * A Base Preferences persistence entity
 */
@DynamoDBDocument
public class BasePreferencesEntity {

	private final static String TENANT_NAME = "tenant";

	public final static String KEY_NAME = "key";

	private String _tenant;

	private String _notificationKey;

	private List<String> _mediums;

	private Date _modified;

	@DynamoDBHashKey(attributeName = TENANT_NAME)
	public String getTenant() {
		return _tenant;
	}

	public void setTenant(String tenant) {
		_tenant = tenant;
	}

	@DynamoDBRangeKey(attributeName = KEY_NAME)
	public String getNotificationKey() {
		return _notificationKey;
	}

	public void setNotificationKey(String notificationKey) {
		_notificationKey = notificationKey;
	}

	public List<String> getMediums() {
		return _mediums;
	}

	public void setMediums(List<String> mediums) {
		_mediums = mediums;
	}

	@DynamoDBTypeConvertedTimestamp
	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	public Date getModified() {
		return _modified;
	}

	public void setModified(Date modified) {
		this._modified = modified;
	}
}