/*
 * Copyright (c) 2018. SailPoint Technologies, Inc. All rights reserved.
 */
package com.sailpoint.audit;

public enum AuditActions {

	//Events classified as USER_MANAGEMENT
	USER_ACTIVATE,
	USER_ACTIVITY_EXPORT,
	USER_ADMIN_GRANT,
	USER_ADMIN_REVOKE,
	USER_DELETE,
	USER_EMAIL_UPDATE,
	USER_HELPDESK_GRANT,
	USER_HELPDESK_REVOKE,
	USER_INVITE,
	USER_INVITE_FAILURE,
	USER_KBA_ANSWER_DELETE,
	USER_KBA_ANSWER_UPDATE,
	USER_KBA_ANSWER_UPDATE_NOTIFICATION,
	USER_KBA_ANSWERS,
	USER_LOCK,
	USER_PASSWORD_RESET_REJECTED,
	USER_PASSWORD_UPDATE,
	USER_PASSWORD_UPDATE_PASSED,
	USER_PASSWORD_UPDATE_FAILED,
	USER_PHONE_UPDATE,
	USER_REGISTRATION,
	USER_REGISTRATION_FAILURE,
	USER_REGISTRATION_LINK,
	USER_RESET,
	USER_STEP_UP_AUTH,
	USER_STEP_UP_AUTH_FAILURE,
	USER_UNLOCK,
	USER_UNLOCK_REJECTED,

	USER_REMOVE,
	USER_DASHBOARD_GRANT,
	USER_DASHBOARD_REVOKE,
	USER_CERT_ADMIN_GRANT,
	USER_CERT_ADMIN_REVOKE,
	USER_REPORT_ADMIN_GRANT,
	USER_REPORT_ADMIN_REVOKE,
	USER_ROLE_ADMIN_GRANT,
	USER_ROLE_ADMIN_REVOKE,
	USER_SOURCE_ADMIN_GRANT,
	USER_SOURCE_ADMIN_REVOKE,

	//Classified as PASSWORD_ACTIVITY
	SOURCE_PASSWORD_INTERCEPT_PROCESSED,
	SOURCE_PASSWORD_INTERCEPT_IGNORED,
	ONBOARDING_TOKEN_GENERATION_PASSED,
	ONBOARDING_TOKEN_GENERATION_FAILED,
	DIGIT_TOKEN_GENERATION_PASSED,
	DIGIT_TOKEN_GENERATION_FAILED,
	ONBOARDING_TOKEN_VERIFICATION_PASSED,
	ONBOARDING_TOKEN_VERIFICATION_FAILED,
	DIGIT_TOKEN_VERIFICATION_PASSED,
	DIGIT_TOKEN_VERIFICATION_FAILED,
	PASSWORD_ORG_CONFIG_CREATE,
	PASSWORD_ORG_CONFIG_UPDATE,
	ONBOARDING_TOKEN_GENERATION_LIMIT_BYPASS,
	CUSTOM_PASSWORD_INSTRUCTIONS_CREATE,
	CUSTOM_PASSWORD_INSTRUCTIONS_DELETE,


	//CERTIFICATION
	CERT_CAMPAIGN_COMPLETE,
	CertificationCampaignDelete,
	CertificationCampaignCreate,
	CertificationCampaignComplete,
	CertificationCampaignActivate,
	STUCK_PENDING_CAMPAIGN_DETECTED,
	CampaignFilterCreate,
	CampaignFilterUpdate,
	CampaignFilterDelete,

	CERT_CAMPAIGN_REVIEW_NOTIFICATION,
	CERTIFICATIONSFINISHED,
	CERT_ITEM_TIMESTAMP_STATS,
	//Classified under type SOURCE
	SOURCE_SCHEMA_ATTRIBUTES_UPDATED,

	IDENTITY_CREATE_PASSED,
	IDENTITY_UPDATE_PASSED,
	IDENTITY_DELETE_PASSED,

	//Lifecycle Change Event
	LIFECYCLE_STATE_CREATE_PASSED,
	LIFECYCLE_STATE_UPDATE_PASSED,
	LIFECYCLE_STATE_DELETE_PASSED,

	IDENTITY_PROFILE_UPDATE,

	ROLE_CREATE_PASSED,
	ROLE_UPDATE_PASSED,
	ROLE_DELETE_PASSED,

	TASK_SCHEDULE_CREATE_PASSED,
	TASK_SCHEDULE_UPDATE_PASSED,
	TASK_SCHEDULE_DELETE_PASSED,

	ACCESS_PROFILE_CREATE_PASSED,
	ACCESS_PROFILE_UPDATE_PASSED,
	ACCESS_PROFILE_DELETE_PASSED,

	//Provisioning
	USER_REMOVE_ACCOUNT,
	ACCOUNT_PROFILE_UPDATED,
	ACCOUNT_PROFILE_CREATED,
	ACCOUNT_PROFILE_DELETED,

	//ACCESS_ITEM
	SetEntitlement,
	APP_UPDATE,
	APP_CREATE,
	APP_DELETE,
	APP_IMPORT,
	APP_SET_ACCESS_PROFILES,
	APP_ADD,
	APP_UPDATE_XML,
	APP_REMOVE,
	APP_PURGED,
	IDENTITY_PROFILE_CONFIGURE_AUTHN,
	AccessRequestConfigUpdated,
	IDENTITY_PROFILE_DELETE,
	IDENTITY_PROFILE_ATTRIBUTES_UPDATED,
	IDENTITY_PROFILE_CREATE,

	//SOURCE
	SOURCE_UPDATE_DELETE_THRESHOLD,
	SOURCE_AGGREGATION_SCHEDULE_UPDATED,
	CONNECTOR_CREATE,
	CONNECTOR_DELETE,
	CONNECTOR_EXPORT,
	CONNECTOR_FILE_UPLOAD,
	CONNECTOR_UPDATE,
	SOURCE_RENAME_FAILURE_DETECTED,

	//AUTH
	IDENTITY_PROVIDER_ENABLED,
	IDENTITY_PROVIDER_EXTERNAL_ENABLED,
	IDENTITY_PROVIDER_EXTERNAL_DISABLED,
	CLIENT_TOKEN_ISSUE,
	SAML_FORCE_AUTHN,
	IDENTITY_PROVIDER_CERTIFICATE_RENEWED,

	//SSO
	APP_LAUNCH_SAML,
	APP_LAUNCH_WSFED,
	APP_USAGE_AGREEMENT,
	APP_LAUNCH_PASSWORD,
	APP_ACCESS_DENIED,
	APP_LAUNCH_NONE,
	APP_LAUNCH_DIR_PSWD,
	SERVICE_PASSWORD_REPLAY,
	SERVICE_PASSWORD_REPLAY_CREDENTIALS_RETRIEVED,

	//IDENTITY_MANAGEMENT
	IdentityDirectCreateFailure,

	//PASSWORD_ACTIVITY
	ACCOUNT_VAULT_UPDATED,
	SOURCE_PASSWORD_POLICY_ASSIGNED,
	REDIRECT_PATTERNS_UPDATED,
	PASSWORD_POLICY_CREATED,
	PASSWORD_POLICY_DELETED,
	PASSWORD_REPLAY_ENABLED,
	INTEGRATION_ENABLED,
	PASSWORD_REPLAY_PASSIVE,
	PASSWORD_POLICY_UPDATED,
	INTEGRATION_DISABLED,
	INTEGRATION_UPDATED,
	ACCOUNT_FULL_RESET,
	MFA_VERIFICATION_FAILED,
	ACCOUNT_PASSWORD_RESET,
	PASSWORD_REPLAY_DISABLED,

	//SYSTEM_CONFIG
	ORG_KBA_ADD,
	ORG_KBA_DELETE,
	API_CLIENT_CREATE,
	API_CLIENT_DELETE,
	BRANDING_CREATE,
	BRANDING_UPDATE,
	BRANDING_DELETE,
	EMAIL_REDIRECTION_ENABLED,
	EMAIL_TEMPLATE_UPDATE,

	RULE_CREATE_PASSED,
	RULE_UPDATE_PASSED,
	RULE_DELETE_PASSED,
}